Add initial code with debug prints
CFC-Servers/cfc_acf_balance pull request #1
Opened 2022-10-12 13:02 UTC by wrefgtzweve

2022-10-15 18:31 UTC, plally requested changes, later dismissed

2022-10-15 18:31 UTC, plally commented on lua/autorun/server/sv_dfa.lua
> +
Why do you need this?

2022-10-15 18:31 UTC, plally commented on lua/autorun/server/sv_dfa.lua
> +        end
you can use elseif

2022-10-15 20:36 UTC, StrawWagen commented on lua/autorun/server/sv_dfa.lua
> +
Applied

2022-10-15 20:36 UTC, StrawWagen commented on lua/autorun/server/sv_dfa.lua
> +        end
Applied

2022-10-16 02:39 UTC, wrefgtzweve commented on lua/autorun/client/cl_dfa.lua
> +end )
![image](https://user-images.githubusercontent.com/69946827/196015256-7278dee8-ce9e-4eb6-a385-139ae3ca4053.png)

2022-10-19 02:29 UTC, merged