Add SetNotSolid detour
CFC-Servers/cfc_acf_balance pull request #12
Opened 2023-07-08 01:08 UTC by wrefgtzweve

2023-07-08 02:13 UTC, brandonsturgeon approved these changes
Think it's worth making this more targeted? Only working on PvP or something like that?

2023-07-08 02:24 UTC, wrefgtzweve commented
> Think it's worth making this more targeted? Only working on PvP or something like that?

i dont think anyone uses this function at all anyways

2023-07-08 20:39 UTC, plally requested changes, later dismissed
test

2023-07-09 21:33 UTC, brandonsturgeon approved these changes
Later, if we have more problems with this, we can make this a PvP specific restriction with state tracking and all that. This is good for now

2023-07-09 21:33 UTC, merged